<a href="https://colab.research.google.com/github/ShijaShaji/Spam-Email-Classification/blob/main/Spam_Email_Classification_using_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [11]:
df = pd.read_csv('spambase_csv.csv')
df.head()

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_%3B,char_freq_%28,char_freq_%5B,char_freq_%21,char_freq_%24,char_freq_%23,capital_run_length_average,capital_run_length_longest,capital_run_length_total,class
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1

In [14]:
rows, cols = df.shape

In [16]:
df.isnull().sum()

word_freq_make                0
word_freq_address             0
word_freq_all                 0
word_freq_3d                  0
word_freq_our                 0
word_freq_over                0
word_freq_remove              0
word_freq_internet            0
word_freq_order               0
word_freq_mail                0
word_freq_receive             0
word_freq_will                0
word_freq_people              0
word_freq_report              0
word_freq_addresses           0
word_freq_free                0
word_freq_business            0
word_freq_email               0
word_freq_you                 0
word_freq_credit              0
word_freq_your                0
word_freq_font                0
word_freq_000                 0
word_freq_money               0
word_freq_hp                  0
word_freq_hpl                 0
word_freq_george              0
word_freq_650                 0
word_freq_lab                 0
word_freq_labs                0
word_freq_telnet              0
word_freq_857                 0
word_freq_data                0
word_freq_415                 0
word_freq_85                  0
word_freq_technology          0
word_freq_1999                0
word_freq_parts               0
word_freq_pm                  0
word_freq_direct              0
word_freq_cs                  0
word_freq_meeting             0
word_freq_original            0
word_freq_project             0
word_freq_re                  0
word_freq_edu                 0
word_freq_table               0
word_freq_conference          0
char_freq_%3B                 0
char_freq_%28                 0
char_freq_%5B                 0
char_freq_%21                 0
char_freq_%24                 0
char_freq_%23                 0
capital_run_length_average    0
capital_run_length_longest    0
capital_run_length_total      0
class                         0
dtype: int64

Dataset has no null values

In [69]:
df["class"].replace({0:-1}, inplace=True)

In [70]:
#Split the data to train and test in the ratio 80-20
trainData = df.sample(frac=0.8, random_state=25)
testData = df.drop(trainData.index)

In [71]:
trainData

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_%3B,char_freq_%28,char_freq_%5B,char_freq_%21,char_freq_%24,char_freq_%23,capital_run_length_average,capital_run_length_longest,capital_run_length_total,class
780,0.17,0.00,0.17,0.0,1.47,0.35,0.00,0.05,0.05,0.05,...,0.010,0.051,0.000,0.010,0.165,0.000,1.790,12,453,1
2487,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.000,0.000,0.000,0.000,1.375,4,11,-1
3099,0.00,0.00,0.00,0.0,0.61,0.00,0.00,0.00,0.00,0.00,...,0.196,0.098,0.000,0.098,0.000,0.000,1.312,6,63,-1
2537,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,1.51,...,0.000,0.000,0.000,0.000,0.000,0.000,1.615,4,21,-1
2532,0.00,0.00,0.00,0.0,0.32,0.32,0.00,0.00,0.00,0.00,...,0.000,0.257,0.000,0.000,0.000,0.000,1.300,7,104,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3497,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.507,0.000,0.000,0.000,0.000,3.041,34,146,-1
2937,0.18,0.00,0.18,0.0,0.00,0.00,0.00,0.00,0.94,0.00,...,0.180,0.167,0.051,0.000,0.025,0.000,4.434,87,909,-1
2040,0.00,1.36,0.90,0.0,0.00,0.00,0.00,0.00,0.00,1.81,...,0.000,0.199,0.000,0.000,0.000,0.000,3.382,53,159,-1
516,0.26,0.72,0.85,0.0,0.00,0.19,0.06,0.33,0.72,0.46,...,0.000,0.131,0.000,0.101,0.101,0.202,4.398,79,1280,1
846,0.00,0.00,0.00,0.0,0.00,0.00,4.54,0.00,0.00,0.00,...,0.000,0.000,0.000,0.000,0.000,0.000,1.800,9,18,1

In [72]:
npTraindata = trainData.to_numpy()
np.random.seed(5)                                      #permuting the dataset in each iteration for better results
npTraindata = np.random.permutation(npTraindata)
npTestData = testData.to_numpy()

In [92]:
X_Train = npTraindata[:,:57]
Y_Train = npTraindata[:,57]
X_Test = npTestData[:,:57]
Y_Test = npTestData[:,57]

In [74]:
Y_Train

array([-1., -1.,  1., ..., -1.,  1.,  1.])

In [93]:
def GaussianNormalisation(dataset):
    #Compute the number of features
    numFeatures = len(dataset[0])
    
    featureMean = np.empty(numFeatures, float)
    featureStd = np.empty(numFeatures, float)
    
    #For every feature
    for i in range(numFeatures):
        #find its Mean and Std
        featureMean[i] = dataset[:,i].mean(axis=0)
        featureStd[i] = dataset[:,i].std(axis=0)
        #Apply Gaussian Noramlisation
        dataset[:,i] = (dataset[:,i] - featureMean[i])/featureStd[i]

    return (featureMean, featureStd)

In [94]:
(featureMean, featureStd) = GaussianNormalisation(X_Train)

In [95]:
# Implement sigmoid function
def sigmoid(x):
    # Bound the argument to be in the interval [-500, 500] to prevent overflow
    x = np.clip( x, -500, 500 )

    return 1/(1 + np.exp(-x))

In [96]:
def logisticRegression(features,labels):
  MaxIter = 20
  lr = 0.01
  b = 0
  numObjects,numFeatures =np.shape(features)
  W = np.zeros(numFeatures)   

  for i in range(1,MaxIter+1):                                                
      for j in range(numObjects):  
         X = features[j] 
         y = labels[j]                   
         a = (np.dot(W.T,X)) +  b                   #calculating activation score
         #update bias and weights   
         W = np.add(W,(lr*y*sigmoid(-y*a)*X))
         b = b + (lr*y*sigmoid(-y*a))

  return b,W

In [97]:
bias , weights = logisticRegression(X_Train, Y_Train)
print(bias,weights)

-1.7906493353323458 [-0.0393234  -0.15091557  0.03605546  0.4850053   0.39498806  0.32042691
  1.02339771  0.25502193  0.11531526  0.08747456 -0.00407126 -0.15259578
 -0.00525933 -0.03427947  0.22299975  0.54222672  0.37582617  0.09603368
  0.08678743  0.74904065  0.1993115   0.41538116  1.01029863  0.58939632
 -2.07157167 -1.12747356 -2.58924699  0.27611429 -0.68131396 -0.39868716
 -0.17825047 -0.24499055 -0.37375846 -0.32869364 -0.75995286  0.39524508
 -0.06473028  0.08586251 -0.19663751 -0.22396416 -0.98827168 -1.25834043
 -0.34966765 -0.7376005  -0.61283298 -1.10305806 -0.10971585 -0.73548761
 -0.41197823  0.0408828  -0.13075514  0.81184223  1.43093023  0.63723025
 -0.26355551  1.1308294   0.4691165 ]

In [102]:
##normalize the test dataset using Means and Std computed on the training dataset
#Compute the number of features
numFeatures = len(X_Test[0]) 
   #For every feature
for i in range(numFeatures):
      #Apply Gaussian Noramlisation with given Mean and Std values
    X_Test[:,i] = (X_Test[:,i] - featureMean[i])/featureStd[i]

Predict the classes of test dataset using the computed bias and weights

In [103]:
def logisticRegressionTest(b, W, obj):
    #Compute the activation score
    a = np.dot(obj, W) + b
    predictedClass = 0
    confidence = 0
    if a > 0:
        predictedClass = +1
        confidence = sigmoid(a)
    else:
        predictedClass = -1
        confidence = 1-sigmoid(a)
    return (predictedClass, confidence)

In [104]:
def evaluationReport(classTrue, classPred):
    positive_mask = classTrue == 1

    # Count the number of elements in the positive class 
    positive = np.count_nonzero(positive_mask)
    # Count True Positive
    tp = np.count_nonzero(classPred[positive_mask]==1)
    # Count False Negative
    fn = np.count_nonzero(classPred[positive_mask]==-1)
    
    negative_mask = classTrue == -1

    # Count the number of elements in the negative class 
    negative = np.count_nonzero(negative_mask)
    # Count False Positive
    fp = np.count_nonzero(classPred[negative_mask]==1)
    # Count True Negative
    tn = np.count_nonzero(classPred[negative_mask]==-1)

    # Compute Accuracy, Precision, Recall, and F-score
    accuracy = (tp + tn)/(tp + tn + fp + fn)
    precision = tp/(tp + fp)
    recall = tp/(tp + fn)
    fscore = 2*precision*recall/(precision + recall)
    print("Evaluation report")
    print("Accuracy: %.2f" % accuracy)
    print("Precision: %.2f" % precision)
    print("Recall: %.2f" % recall)
    print("F-score: %.2f" % fscore)

In [105]:
classTrue = np.array([int(x) for x in Y_Test], dtype=int)
classPred = np.array([int(logisticRegressionTest(bias,weights,X)[0]) for X in X_Test], dtype=int)
evaluationReport(classTrue, classPred)

Evaluation report
Accuracy: 0.92
Precision: 0.91
Recall: 0.88
F-score: 0.90